author: MingxuanGame

keywords: nonebot, Python, Go, cqhttp, onebot

description: MingxuanGame's blog, code for fun.

# 导航栏头部名称
nav_name: MingxuanGame

# 导航栏座右铭
motto: "Want to do everything, but do nothing."

github: "https://github.com/MingxuanGame"

# 站点图标和APP图标
favicon:
  icon: /images/favicon.jpg
  touch_icon: /images/favicon.jpg

# RSS文件位置
rss:

# 自定义样式文件
custom_styles:

# 自定义脚本文件
custom_scripts:

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "MingxuanGame"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 </a>国际许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2022-09-08"

# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Xqx314bLUnrL2wetLC03Ofhu-MdYXbMMI
  appkey: kQXnQs2wtu271vKEaJXDnVnN
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.count为true
welcome:
  enable: true
  interval: 30

# 需要保证leancloud.comment为false
disqus:
  enable: false
  id:

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
# passwords:
#   - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: true
  facebook: true
  weibo: true
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id:
  "360":
    enable: false
    id:

# 打赏图片
reward:
  enable: false
  qrcodes:
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn:
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

friends:
  # 我也不知道为什么把我自己放在前面又不显示出来
  # termux 物理键盘没法打中文有点难受
  - nickname: MingxuanGame
    avatar: /images/favicon.jpg
    site: https://blog.mxgame.top
    meta: 我自己！
    show: false
  - nickname: 津轻年回
    avatar: https://avatars.githubusercontent.com/u/30568146
    site: https://blog.nranp.com/
    meta: 数据系大佬年回！
    show: true
  - nickname: Bob
    avatar: https://avatars.githubusercontent.com/u/66893970
    site: https://blog.beimo2007.top/
    meta: 同龄人！系统内核开发者！
    show: true
  - nickname: 摸鱼
    avatar: https://avatars.githubusercontent.com/u/61240774
    site: https://blog.kifuan.me/
    meta: 摸鱼大佬，高技术力雏草姬，~~何同学真爱粉~~
    show: true

footer:
  - title: "OneBot & NoneBot"
    children:
      - name: "OneBot"
        path: "https://onebot.dev/"
      - name: "go-cqhttp"
        path: "https://docs.go-cqhttp.org/"
      - name: "NoneBot2"
        path: "https://v2.nonebot.dev/"
      - name: "NoneBot1"
        path: "https://docs.nonebot.dev/"
  - title: "Mirai & GraiaProject"
    children:
      - name: "Mirai"
        path: "https://mirai.mamoe.net/"
      - name: "Mirai-API-HTTP"
        path: "https://docs.mirai.mamoe.net/mirai-api-http/"
      - name: "Graia Project"
        path: "https://graia.readthedocs.io/"
      - name: "GraiaCommunity Docs"
        path: "https://graiax.cn/"
  - title: "Contact me"
    children:
      - name: "QQ: 1060148379"
        path: "tencent://message/?uin=1060148379"
      - name: "GitHub: MingxuanGame"
        path: "http://github.com/MingxuanGame"

footer_contact: "MingxuanGame@outlook.com"
